name       : gl-driver-switch
version    : 2
release    : 4
source     :
    - https://github.com/solus-project/gl-driver-switch/releases/download/v2/gl-driver-switch-2.tar.xz : 6d609ec57e18d7c093d46ba1f0e3714c29eeff61f02c86d370f9743277cd4f4a
license    : GPL-2.0
summary    : GL Driver Switch Utility
description: |
    GL Driver Switch Utility
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
