name       : gl-driver-switch
version    : 1
release    : 3
source     :
    - https://github.com/solus-project/gl-driver-switch/releases/download/v1/gl-driver-switch-1.tar.xz : 00c5f5b78367cf43cd2284a4f95e4b3c29d1c64dad5d8b56e88e1a1db500fe18
license    : GPL-2.0
summary    : GL Driver Switch Utility
description: |
    GL Driver Switch Utility
builddeps  :
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-enormous-path_exists-issue-broken-symlinks.patch
    %configure
build      : |
    %make
install    : |
    %make_install
